const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getUsage: () => ipcRenderer.invoke('get-usage'),
  getTemps: () => ipcRenderer.invoke('get-temps'),
  resizeHeight: (h) => ipcRenderer.send('resize-height', h),
  runMaintenance: () => ipcRenderer.invoke('run-maintenance'),
  getMaintenance: () => ipcRenderer.invoke('get-maintenance'),
  getAuth: () => ipcRenderer.invoke('get-auth'),
  setAuth: (opts) => ipcRenderer.invoke('set-auth', opts),
  closeApp: () => ipcRenderer.send('close-app'),
  tecladoTravar: (seg) => ipcRenderer.invoke('teclado-travar', seg),
  tecladoSoltar: () => ipcRenderer.invoke('teclado-soltar'),
  tecladoEstado: () => ipcRenderer.invoke('teclado-estado'),
  telasDormir: () => ipcRenderer.invoke('telas-dormir'),
  painelReiniciar: () => ipcRenderer.invoke('painel-reiniciar'),
  sentryGet: () => ipcRenderer.invoke('sentry-get'),
  sentryRefresh: () => ipcRenderer.invoke('sentry-refresh'),
  sentrySeen: () => ipcRenderer.invoke('sentry-seen'),
  sentryResolve: (id, status) => ipcRenderer.invoke('sentry-resolve', id, status),
  sentryOpen: (url) => ipcRenderer.send('sentry-open', url),
  sentryDetalhe: (id) => ipcRenderer.invoke('sentry-detalhe', id),
  // O main empurra a lista a cada varredura; nao precisa o renderer ficar pedindo.
  onSentry: (cb) => ipcRenderer.on('sentry-update', (e, payload) => cb(payload)),
  discordGet: () => ipcRenderer.invoke('discord-get'),
  discordRefresh: () => ipcRenderer.invoke('discord-refresh'),
  discordSeen: () => ipcRenderer.invoke('discord-seen'),
  discordRecount: () => ipcRenderer.invoke('discord-recount'),
  discordReagir: (id, emoji) => ipcRenderer.invoke('discord-reagir', id, emoji),
  discordTopico: (id, nome, resposta) => ipcRenderer.invoke('discord-topico', id, nome, resposta),
  discordReagir: (id, emoji) => ipcRenderer.invoke('discord-reagir', id, emoji),
  discordTopico: (id, nome, resposta) => ipcRenderer.invoke('discord-topico', id, nome, resposta),
  onDiscord: (cb) => ipcRenderer.on('discord-update', (e, payload) => cb(payload)),
  abrirUrl: (url) => ipcRenderer.send('abrir-url', url),
  txCred: () => ipcRenderer.invoke('tx-cred'),
  txPing: (host, porta) => ipcRenderer.invoke('tx-ping', host, porta),
  alertaConsole: (dados) => ipcRenderer.send('alerta-console', dados),
  diag: (texto) => ipcRenderer.send('diag', texto),
  fonteLog: () => ipcRenderer.invoke('fonte-log'),
  telaEstado: (i, r) => ipcRenderer.send('tela-estado', i, r),
  servGet: () => ipcRenderer.invoke('serv-get'),
  servSet: (lista) => ipcRenderer.invoke('serv-set', lista),
  devProjetos: () => ipcRenderer.invoke('dev-projetos'),
  devSubir: (pasta, avd, alvo) => ipcRenderer.invoke('dev-subir', pasta, avd, alvo),
  devMatar: (pasta) => ipcRenderer.invoke('dev-matar', pasta),
  devEncaixar: (caixa) => ipcRenderer.invoke('dev-encaixar', caixa),
  devMostrar: (mostrar) => ipcRenderer.invoke('dev-mostrar', mostrar),
  onDevLog: (cb) => ipcRenderer.on('dev-log', (e, linha) => cb(linha))
});
